### PR TITLE
Add a library function to add a subnet to an existing network.

### PR DESCRIPTION
**Pull request by pedro-r-marques**

### CODE REVIEW

**Comment by nati** [comment]
it looks like we are adding integration test in this commit.
it is better to mention it in the commit msg & have a instruction for how to run integration test in README

**Comment by pedro-r-marques** [comment]
This commit disables the integration tests unless a flag is given to the test.

**Comment by nati** [comment]
ah I got it. I still think it is helpful to have doc about it in Readme.md but it up to you.

LGTM

**Comment by pedro-r-marques** [comment]
@nati Somehow your review comments disappeared from the conversation when updated the review.

**Pull request merged**
